title: Writ 1 <br> Fall 2021 Section 1
logo: /images/phys-logo.png
description: Harvey Mudd College
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
relative_links:
  enabled:     true
  collections: false
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
  